name: tamil_setu
description: A Hindi-to-Tamil learning app.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  confetti: ^0.7.0
  cupertino_icons: ^1.0.2
  flutter_tts: ^4.2.3
  provider: ^6.1.5+1
  shared_preferences: ^2.5.4
  audioplayers: ^6.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: "^0.13.1"
  golden_screenshot: ^7.2.0

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/app_icon.png"
  adaptive_icon_background: "#005DAA" # Your Peacock Blue
  adaptive_icon_foreground: "assets/images/app_icon_foreground.png"
  
flutter:
  uses-material-design: true
  assets:
    - assets/audio/
    - assets/data/master_content.json
    - assets/images/
  fonts:
    - family: NotoSansHindi
      fonts:
        - asset: assets/fonts/NotoSansDevanagari-Regular.ttf
    - family: NotoSansTamil
      fonts:
        - asset: assets/fonts/NotoSansTamil-Regular.ttf
